name: Improvement
description: Suggest an improvement
title: "[Improvement]: "
labels: ["improvement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest this improvement!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Suggested Improvement
      description: Please describe the suggested improvement
      placeholder: "For the ... pattern at this location ... I sugggest the following improvement:"
    validations:
      required: true
